version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - appnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coworking_space
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:
